### ISSUE TITLE
Name field not being populated

### ISSUE THREAD

**Issue by myaple** [ZeroQI/YouTube-Agent.bundle#131]
The relevant com.plexapp.agents.youtube.log:

`2023-05-17 20:48:14,194 (14888a7feb30) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.youtube/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgpiNjQ4YzkzMDAwODVjMTU1czE3Cm9wZW5TdWJ0aXRsZXNIYXNobnM0Cm5hbWVzNjUKJTJGeW91dHViZSUyRmNoYW5uZWxzJTJGQ3J1aXNpbmdUaGVDdXQlMkYlNUJWckltU2p4R3h0WSU1RCUyRXdlYm1zOApmaWxlbmFtZXM0MAoxNTMzNzM4ZmRiY2U5OTA0MDdkNTcxNzVmMzQxYzk3NGNiMWQ4NzVlczgKcGxleEhhc2hzNwoxMzA4MzYxczgKZHVyYXRpb25zNQo0MzA0NnMyCmlkcjAK
2023-05-17 20:48:14,194 (14888a7feb30) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2023-05-17 20:48:14,195 (14888a7feb30) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.youtube/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgpiNjQ4YzkzMDAwODVjMTU1czE3Cm9wZW5TdWJ0aXRsZXNIYXNobnM0Cm5hbWVzNjUKJTJGeW91dHViZSUyRmNoYW5uZWxzJTJGQ3J1aXNpbmdUaGVDdXQlMkYlNUJWckltU2p4R3h0WSU1RCUyRXdlYm1zOApmaWxlbmFtZXM0MAoxNTMzNzM4ZmRiY2U5OTA0MDdkNTcxNzVmMzQxYzk3NGNiMWQ4NzVlczgKcGxleEhhc2hzNwoxMzA4MzYxczgKZHVyYXRpb25zNQo0MzA0NnMyCmlkcjAK
2023-05-17 20:48:14,196 (14888a7feb30) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': 'b648c9300085c155', 'name': None, 'filename': '%2Fyoutube%2Fchannels%2FCruisingTheCut%2F%5BVrImSjxGxtY%5D%2Ewebm', 'plexHash': '1533738fdbce990407d57175f341c974cb1d875e', 'duration': '1308361', 'id': '43046'}
2023-05-17 20:48:14,197 (14888a7feb30) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/library/metadata/43046/tree'
2023-05-17 20:48:14,205 (14888a7feb30) :  CRITICAL (agentkit:1018) - Exception in the search function of agent named 'YouTubeMovie', called with keyword arguments {'openSubtitlesHash': 'b648c9300085c155', 'name': None, 'filename': '%2Fyoutube%2Fchannels%2FCruisingTheCut%2F%5BVrImSjxGxtY%5D%2Ewebm', 'plexHash': '1533738fdbce990407d57175f341c974cb1d875e', 'duration': '1308361', 'id': '43046'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-86cfcc10c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Plex Media Server/Plug-ins/YouTube-Agent.bundle/Contents/Code/__init__.py", line 556, in search
    def search (self, results,  media, lang, manual):  Search (results,  media, lang, manual, True)
  File "/config/Plex Media Server/Plug-ins/YouTube-Agent.bundle/Contents/Code/__init__.py", line 120, in Search
    displayname = sanitize_path(os.path.basename(media.name if movie else media.show))
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

2023-05-17 20:48:14,206 (14888a7feb30) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-05-17 20:48:14,206 (14888a7feb30) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes`

YouTube-Agent.bundle version: Jan 20th, current master
PMS version: 1.32.2.7002

Issue:

When I load in a library of youtube videos, my agent is no longer able to match them. This started after I upgraded PMS from 1.31.xxx, pre-SSL error, to 1.32.2.7002, post-SSL fix. When I manually type in the Youtube ID into the name field in the match, it works perfectly, but it won't auto match because the name field is None.
